In this we will clean

In [74]:
import numpy as np
import pandas as pd

In [75]:
df = pd.read_csv(r"..\dataset\raw_data_1\sales_data.csv")

In [76]:
df

,Price,Close,High,Low,Open,Volume
0,Ticker,AAPL,AAPL,AAPL,AAPL,AAPL
1,Date,NaN,NaN,NaN,NaN,NaN
2,2020-01-02,72.46826171875,72.52858156247073,71.22325926076245,71.4765996590847,135480400
3,2020-01-03,71.76371765136719,72.52374615608241,71.53932961570813,71.6961597256872,146322800
4,2020-01-06,72.33556365966797,72.37416924858576,70.63454677653742,70.88547942287144,118387200
...,...,...,...,...,...,...
1255,2024-12-24,257.0375061035156,257.04744042152294,254.14058909817473,254.3397007808045,23234700
1256,2024-12-26,257.8537902832031,258.9289447577566,256.4700643478404,257.02754060124687,27237100
1257,2024-12-27,254.43923950195312,257.53525297634997,251.92063167469624,256.66914450564,42355300
1258,2024-12-30,251.06451416015625,252.35866419404098,249.62104554893796,251.09437787562297,35557500
1259,2024-12-31,249.29251098632812,252.1396347735265,248.30696287880588,251.30342042234355,39480700

In [77]:
df.columns

Index(['Price', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')

In [78]:
##rename Price to date
df = df.rename(columns={"Price": "Date"})

In [79]:
df.columns

Index(['Date', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')

In [80]:
df.isnull().sum()

Date      0
Close     1
High      1
Low       1
Open      1
Volume    1
dtype: int64

In [81]:
##delete the satrting 2 row , coz its useless
df = df.drop(index=[0, 1]).reset_index(drop=True)

In [82]:
df

,Date,Close,High,Low,Open,Volume
0,2020-01-02,72.46826171875,72.52858156247073,71.22325926076245,71.4765996590847,135480400
1,2020-01-03,71.76371765136719,72.52374615608241,71.53932961570813,71.6961597256872,146322800
2,2020-01-06,72.33556365966797,72.37416924858576,70.63454677653742,70.88547942287144,118387200
3,2020-01-07,71.9953384399414,72.60094451443848,71.77577337938688,72.34518902923438,108872000
4,2020-01-08,73.15348815917969,73.45508735263148,71.6985739444987,71.6985739444987,132079200
...,...,...,...,...,...,...
1253,2024-12-24,257.0375061035156,257.04744042152294,254.14058909817473,254.3397007808045,23234700
1254,2024-12-26,257.8537902832031,258.9289447577566,256.4700643478404,257.02754060124687,27237100
1255,2024-12-27,254.43923950195312,257.53525297634997,251.92063167469624,256.66914450564,42355300
1256,2024-12-30,251.06451416015625,252.35866419404098,249.62104554893796,251.09437787562297,35557500
1257,2024-12-31,249.29251098632812,252.1396347735265,248.30696287880588,251.30342042234355,39480700

In [83]:
df.dtypes

Date      object
Close     object
High      object
Low       object
Open      object
Volume    object
dtype: object

In [84]:
##as datatype are not suitable for ploting so convert into int or float
df["Date"] = pd.to_datetime(df["Date"])

numeric_column = ["Close", "High", "Low", "Open", "Volume"]
df[numeric_column] = df[numeric_column].astype(float)

In [85]:
df.dtypes

Date      datetime64[ns]
Close            float64
High             float64
Low              float64
Open             float64
Volume           float64
dtype: object

In [86]:
## sort date sequencely may be in between it might be different

df = df.sort_values("Date").reset_index(drop=True)

In [87]:
df

           Date       Close        High         Low        Open       Volume
0    2020-01-02   72.468262   72.528582   71.223259   71.476600  135480400.0
1    2020-01-03   71.763718   72.523746   71.539330   71.696160  146322800.0
2    2020-01-06   72.335564   72.374169   70.634547   70.885479  118387200.0
3    2020-01-07   71.995338   72.600945   71.775773   72.345189  108872000.0
4    2020-01-08   73.153488   73.455087   71.698574   71.698574  132079200.0
...         ...         ...         ...         ...         ...          ...
1253 2024-12-24  257.037506  257.047440  254.140589  254.339701   23234700.0
1254 2024-12-26  257.853790  258.928945  256.470064  257.027541   27237100.0
1255 2024-12-27  254.439240  257.535253  251.920632  256.669145   42355300.0
1256 2024-12-30  251.064514  252.358664  249.621046  251.094378   35557500.0
1257 2024-12-31  249.292511  252.139635  248.306963  251.303420   39480700.0

[1258 rows x 6 columns]

In [88]:
df.isnull().sum()  ##removed earlyier in row 0 & 1

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [89]:
## think of that price < 0 , high < low...etc for this we do sanity check . it should come 0

(df[["Close", "High", "Low", "Open", "Volume"]] <= 0).sum()

Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [90]:
df = df.set_index("Date")

In [91]:
df

                 Close        High         Low        Open       Volume
Date
2020-01-02   72.468262   72.528582   71.223259   71.476600  135480400.0
2020-01-03   71.763718   72.523746   71.539330   71.696160  146322800.0
2020-01-06   72.335564   72.374169   70.634547   70.885479  118387200.0
2020-01-07   71.995338   72.600945   71.775773   72.345189  108872000.0
2020-01-08   73.153488   73.455087   71.698574   71.698574  132079200.0
...                ...         ...         ...         ...          ...
2024-12-24  257.037506  257.047440  254.140589  254.339701   23234700.0
2024-12-26  257.853790  258.928945  256.470064  257.027541   27237100.0
2024-12-27  254.439240  257.535253  251.920632  256.669145   42355300.0
2024-12-30  251.064514  252.358664  249.621046  251.094378   35557500.0
2024-12-31  249.292511  252.139635  248.306963  251.303420   39480700.0

[1258 rows x 5 columns]

In [92]:
df.info

<bound method DataFrame.info of                  Close        High         Low        Open       Volume
Date
2020-01-02   72.468262   72.528582   71.223259   71.476600  135480400.0
2020-01-03   71.763718   72.523746   71.539330   71.696160  146322800.0
2020-01-06   72.335564   72.374169   70.634547   70.885479  118387200.0
2020-01-07   71.995338   72.600945   71.775773   72.345189  108872000.0
2020-01-08   73.153488   73.455087   71.698574   71.698574  132079200.0
...                ...         ...         ...         ...          ...
2024-12-24  257.037506  257.047440  254.140589  254.339701   23234700.0
2024-12-26  257.853790  258.928945  256.470064  257.027541   27237100.0
2024-12-27  254.439240  257.535253  251.920632  256.669145   42355300.0
2024-12-30  251.064514  252.358664  249.621046  251.094378   35557500.0
2024-12-31  249.292511  252.139635  248.306963  251.303420   39480700.0

[1258 rows x 5 columns]>

In [93]:
df.head()

                Close       High        Low       Open       Volume
Date
2020-01-02  72.468262  72.528582  71.223259  71.476600  135480400.0
2020-01-03  71.763718  72.523746  71.539330  71.696160  146322800.0
2020-01-06  72.335564  72.374169  70.634547  70.885479  118387200.0
2020-01-07  71.995338  72.600945  71.775773  72.345189  108872000.0
2020-01-08  73.153488  73.455087  71.698574  71.698574  132079200.0

In [94]:
df.tail()

                 Close        High         Low        Open      Volume
Date
2024-12-24  257.037506  257.047440  254.140589  254.339701  23234700.0
2024-12-26  257.853790  258.928945  256.470064  257.027541  27237100.0
2024-12-27  254.439240  257.535253  251.920632  256.669145  42355300.0
2024-12-30  251.064514  252.358664  249.621046  251.094378  35557500.0
2024-12-31  249.292511  252.139635  248.306963  251.303420  39480700.0

In [95]:
## dont forget to save cleaned dataset for further opertions in other file or folder

df.to_csv(r"..\dataset\cleaned_data_2\sale_data_cleaned.csv")

In [96]:
## in next folder to get cleaned file use :
# df = pd.read_csv(
#     "../dataset/cleaned/sales_data_cleaned.csv",
#     parse_dates=['Date'],
#     index_col='Date'
# )